name = "enamel-quote-proxy"
main = "index.js"
compatibility_date = "2024-01-01"

[[kv_namespaces]]
binding = "RATE_LIMIT"
id = "58a30886644d40f9bbefb0617e5509d1"

[vars]
GITHUB_OWNER = "fnsservicebot-max"
GITHUB_REPO = "enamel-quote-system"
